# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: "Star Wars" }, { name: "Lord of the Rings" }])
#   Character.create(name: "Luke", movie: movies.first)


# Clear existing data to prevent duplicates
User.destroy_all
Workout.destroy_all
Exercise.destroy_all
WorkoutExercise.destroy_all
SetEntry.destroy_all

# Create two users
users = [
  User.create!(name: 'Alice Johnson', email: 'alice@example.com', avatar: 'https://via.placeholder.com/150'),
  User.create!(name: 'Bob Smith', email: 'bob@example.com', avatar: 'https://via.placeholder.com/150')
]

# Create exercises
exercises = [
  Exercise.create!(name: 'barbell bench press', description: ["Lie flat on a bench with your feet flat on the ground and your back pressed against the bench.","Grasp the barbell with an overhand grip slightly wider than shoulder-width apart.","Lift the barbell off the rack and hold it directly above your chest with your arms fully extended.","Lower the barbell slowly towards your chest, keeping your elbows tucked in.","Pause for a moment when the barbell touches your chest.","Push the barbell back up to the starting position by extending your arms.","Repeat for the desired number of repetitions."], muscle_group: 'pectorals', api_key: "0025"),
  Exercise.create!(name: 'smith deadlift', description: ["Set up the smith machine with the bar at hip height.","Stand with your feet shoulder-width apart, toes pointing slightly outward.","Bend at the hips and knees, keeping your back straight and chest up, and grip the bar with an overhand grip slightly wider than shoulder-width apart.","Engage your core and lift the bar by extending your hips and knees, keeping the bar close to your body.","Stand up straight, fully extending your hips and knees.","Lower the bar back down by bending at the hips and knees, maintaining control and keeping your back straight.","Repeat for the desired number of repetitions."], muscle_group: 'glutes', api_key: "0752"),
  Exercise.create!(name: 'cable upper row', description: ["Attach a straight bar to a cable machine at chest height.","Stand facing the machine with your feet shoulder-width apart.","Grasp the bar with an overhand grip, hands slightly wider than shoulder-width apart.","Keep your back straight and your core engaged.","Pull the bar towards your upper chest, squeezing your shoulder blades together.","Pause for a moment at the top of the movement.","Slowly release the bar back to the starting position.","Repeat for the desired number of repetitions."], muscle_group: 'upper back', api_key: "1324"),
  Exercise.create!(name: 'smith chair squat', description: ["Adjust the height of the smith machine bar to a comfortable position.","Stand with your feet shoulder-width apart, toes slightly turned out.","Place the barbell across your upper back, resting it on your traps.","Engage your core and keep your chest up as you slowly lower your body by bending your knees and hips.","Continue lowering until your thighs are parallel to the ground, or as low as you can comfortably go.","Pause for a moment, then push through your heels to return to the starting position.","Repeat for the desired number of repetitions."], muscle_group: 'quads', api_key: "0750"),
  Exercise.create!(name: 'dumbbell fly', description: ["Lie flat on a bench with a dumbbell in each hand, palms facing each other.","Extend your arms straight up over your chest, with a slight bend in your elbows.","Keeping a slight bend in your elbows, lower your arms out to the sides in a wide arc until you feel a stretch in your chest.","Pause for a moment, then reverse the movement and bring the dumbbells back up to the starting position.","Repeat for the desired number of repetitions."], muscle_group: 'pectorals', api_key: "0308"),
  Exercise.create!(name: 'cable seated row', description: ["Sit on the cable row machine with your feet flat on the footrests and your knees slightly bent.","Grasp the handles with an overhand grip, keeping your back straight and your shoulders relaxed.","Pull the handles towards your body, squeezing your shoulder blades together.","Pause for a moment at the peak of the movement, then slowly release the handles back to the starting position.","Repeat for the desired number of repetitions."], muscle_group: 'upper back', api_key: "0861"),
  Exercise.create!(name: 'hyperextension', description: ["Adjust the hyperextension bench so that your upper thighs are resting on the pad and your feet are secured.","Cross your arms over your chest or place your hands behind your head.","Lower your upper body towards the ground while keeping your back straight.","Pause for a moment at the bottom, then raise your upper body back up until it is in line with your legs.","Repeat for the desired number of repetitions."], muscle_group: 'spine', api_key: "0489"),
  Exercise.create!(name: 'chest dip', description: ["Position yourself on parallel bars with your arms fully extended and your body straight.","Lower your body by bending your elbows until your shoulders are below your elbows.","Push yourself back up to the starting position by straightening your arms.","Repeat for the desired number of repetitions."], muscle_group: 'pectorals', api_key: "0251"),
  Exercise.create!(name: 'dumbbell incline shoulder raise', description: ["Set an incline bench to a 45-degree angle and sit on it with a dumbbell in each hand, palms facing down.","Rest the dumbbells on your thighs and lean back onto the bench.","Use your thighs to help raise the dumbbells to shoulder height, then rotate your wrists so that your palms are facing forward.","Exhale and slowly raise the dumbbells above your head, keeping a slight bend in your elbows.","Pause for a moment at the top, then inhale and slowly lower the dumbbells back to shoulder height.","Repeat for the desired number of repetitions."], muscle_group: 'serratus anterior', api_key: "0328"),
  Exercise.create!(name: 'assisted standing chin-up', description: ["Adjust the machine to your desired assistance level.","Stand on the foot platform and grip the handles with an overhand grip, slightly wider than shoulder-width apart.","Keep your chest up and shoulders back, engage your core, and slightly bend your knees.","Pull your body up by flexing your elbows and driving your elbows down towards your sides.","Continue pulling until your chin is above the bar.","Pause for a moment at the top, then slowly lower your body back down to the starting position.","Repeat for the desired number of repetitions."], muscle_group: 'lats', api_key: "1431"),
  Exercise.create!(name: 'assisted standing pull-up', description: ["Adjust the machine to your desired weight and height settings.","Stand facing the machine with your feet shoulder-width apart.","Grasp the handles with an overhand grip, slightly wider than shoulder-width apart.","Engage your lats and biceps, and pull yourself up towards the handles.","Pause for a moment at the top, squeezing your back muscles.","Slowly lower yourself back down to the starting position.","Repeat for the desired number of repetitions."], muscle_group: 'lats', api_key: "1432"),
  Exercise.create!(name: 'lever seated hip adduction', description: ["Adjust the seat height and position yourself on the machine with your back against the backrest.","Place your feet on the footrests and grasp the handles for stability.","Engage your adductor muscles and slowly bring your legs together, squeezing your inner thighs.","Pause for a moment at the peak contraction, then slowly return to the starting position.","Repeat for the desired number of repetitions."], muscle_group: 'adductors', api_key: "0598"),
  Exercise.create!(name: 'lever seated hip abduction', description: ["Adjust the seat height so that your knees are at a 90-degree angle.","Sit on the machine with your back against the backrest and your feet on the footrests.","Place your hands on the side handles for stability.","Engage your abductors and slowly push your legs apart, away from the midline of your body.","Pause for a moment at the end of the movement, then slowly bring your legs back together to the starting position.","Repeat for the desired number of repetitions."], muscle_group: 'abductors', api_key: "0597"),
  Exercise.create!(name: 'cable hip adduction', description: ["Attach the ankle cuff to your ankle and stand facing the cable machine.","Position yourself far enough away from the machine so that there is tension on the cable.","Place your hands on the machine for support.","Keeping your leg straight, slowly move your leg across your body towards the midline.","Pause for a moment at the end of the movement, then slowly return to the starting position.","Repeat for the desired number of repetitions."], muscle_group: 'adductors', api_key: "0168"),
  Exercise.create!(name: 'band assisted pull-up', description: ["Attach the band to a pull-up bar or sturdy anchor point.","Step onto the band and grip the bar with your palms facing away from you, hands slightly wider than shoulder-width apart.","Hang with your arms fully extended, keeping your core engaged and your shoulders down and back.","Pull your body up towards the bar by squeezing your shoulder blades together and driving your elbows down towards your hips.","Continue pulling until your chin is above the bar, then slowly lower yourself back down to the starting position.","Repeat for the desired number of repetitions."], muscle_group: 'lats', api_key: "0970"),
  Exercise.create!(name: 'handstand', description: ["Find an open space with enough room to perform a handstand.","Place your hands on the ground shoulder-width apart, fingers pointing forward.","Kick your legs up towards the wall, using your core and shoulders to maintain balance.","Once in a handstand position, engage your triceps to support your body weight.","Hold the handstand for as long as you can maintain balance.","To come down, slowly lower your legs back to the ground.","Repeat for the desired number of repetitions."], muscle_group: 'triceps', api_key: "3302"),
  Exercise.create!(name: 'close grip chin-up', description: ["Grab the pull-up bar with your palms facing towards you and your hands shoulder-width apart.","Hang from the bar with your arms fully extended and your feet off the ground.","Engage your back muscles and pull your body up towards the bar, keeping your elbows close to your body.","Continue pulling until your chin is above the bar.","Pause for a moment at the top, then slowly lower your body back down to the starting position.","Repeat for the desired number of repetitions."], muscle_group: 'lats', api_key: "1327"),
  Exercise.create!(name: 'hanging leg raise', description: ["Hang from a pull-up bar with your arms fully extended and your palms facing away from you.","Engage your core and lift your legs up in front of you, keeping them straight.","Continue lifting until your legs are parallel to the ground or as high as you can comfortably go.","Pause for a moment at the top, then slowly lower your legs back down to the starting position.","Repeat for the desired number of repetitions."], muscle_group: 'abs', api_key: "0472"),
  Exercise.create!(name: 'wide grip pull-up', description: ["Hang from a pull-up bar with your palms facing away from you and your hands wider than shoulder-width apart.","Engage your core and squeeze your shoulder blades together.","Pull your body up towards the bar until your chin is above the bar.","Lower your body back down to the starting position with control.","Repeat for the desired number of repetitions."], muscle_group: 'lats', api_key: "1429"),
  Exercise.create!(name: 'chin-up', description: ["Hang from a pull-up bar with your palms facing towards you and your hands shoulder-width apart.","Engage your core and pull your body up towards the bar, leading with your chest.","Continue pulling until your chin is above the bar.","Pause for a moment at the top, then slowly lower your body back down to the starting position.","Repeat for the desired number of repetitions."], muscle_group: 'lats', api_key: "1326"),
  Exercise.create!(name: 'wheel rollerout', description: ["Kneel on the floor and place the wheel roller in front of you.","Place your hands on the handles of the wheel roller and extend your arms straight out in front of you.","Engage your core muscles and slowly roll the wheel forward, keeping your back straight and your abs tight.","Continue rolling forward until your body is fully extended and your arms are overhead.","Pause for a moment, then slowly roll the wheel back towards your knees, maintaining control and keeping your abs engaged.","Repeat for the desired number of repetitions."], muscle_group: 'abs', api_key: "0857"),
  Exercise.create!(name: 'dumbbell decline bench press', description: ["Lie down on a decline bench with your feet secured and your head lower than your hips.","Hold a dumbbell in each hand and extend your arms straight up above your chest, palms facing forward.","Lower the dumbbells slowly to the sides of your chest, keeping your elbows at a 90-degree angle.","Push the dumbbells back up to the starting position, fully extending your arms.","Repeat for the desired number of repetitions."], muscle_group: 'pectorals', api_key: "0301"),
  Exercise.create!(name: 'upward facing dog', description: ["Lie face down on the floor with your legs extended behind you.","Place your hands on the floor next to your lower ribs, fingers pointing forward.","Press your hands firmly into the floor and straighten your arms, lifting your torso and thighs off the ground.","Roll your shoulders back and down, opening your chest and lifting your gaze towards the ceiling.","Hold this position for a few breaths, then slowly lower your body back down to the starting position.","Repeat for the desired number of repetitions."], muscle_group: 'spine', api_key: "1366"),
  Exercise.create!(name: 'dumbbell bench press', description: ["Lie flat on a bench with your feet flat on the ground and your back pressed against the bench.","Hold a dumbbell in each hand, with your palms facing forward and your arms extended above your chest.","Lower the dumbbells slowly to the sides of your chest, keeping your elbows at a 90-degree angle.","Pause for a moment, then push the dumbbells back up to the starting position, fully extending your arms.","Repeat for the desired number of repetitions."], muscle_group: 'pectorals', api_key: "0289"),
  Exercise.create!(name: 'barbell lying triceps extension', description: ["Lie flat on a bench with your feet flat on the ground and your head at the end of the bench.","Hold the barbell with an overhand grip, hands shoulder-width apart, and extend your arms straight up over your chest.","Keeping your upper arms stationary, slowly lower the barbell towards your forehead by bending your elbows.","Pause for a moment at the bottom, then extend your arms back up to the starting position.","Repeat for the desired number of repetitions."], muscle_group: 'triceps', api_key: "0061"),
  Exercise.create!(name: 'reverse crunch', description: ["Lie flat on your back with your arms extended along your sides.","Bend your knees and lift your feet off the ground, bringing your thighs perpendicular to the floor.","Contract your abs and curl your hips off the floor, bringing your knees towards your chest.","Pause for a moment at the top, then slowly lower your hips back down to the starting position.","Repeat for the desired number of repetitions."], muscle_group: 'abs', api_key: "0872"),
  Exercise.create!(name: 'cross body crunch', description: ["Lie flat on your back with your knees bent and feet flat on the ground.","Place your hands behind your head with your elbows pointing outwards.","Engaging your abs, lift your upper body off the ground and twist to bring your right elbow towards your left knee.","Pause for a moment at the top, then slowly lower your upper body back down to the starting position.","Repeat on the other side, bringing your left elbow towards your right knee.","Repeat for the desired number of repetitions."], muscle_group: 'abs', api_key: "0262"),
  Exercise.create!(name: 'leg up hamstring stretch', description: ["Lie flat on your back with your legs extended.","Bend one knee and bring it towards your chest, holding onto your thigh or shin.","Straighten your leg as much as possible while keeping it elevated.","Hold the stretch for 20-30 seconds.","Repeat with the other leg."], muscle_group: 'hamstrings', api_key: "1576"),
  Exercise.create!(name: 'barbell decline bench press', description: ["Lie on a decline bench with your feet secured and your head lower than your hips.","Grasp the barbell with an overhand grip slightly wider than shoulder-width apart.","Unrack the barbell and lower it slowly towards your chest, keeping your elbows tucked in.","Pause for a moment at the bottom, then push the barbell back up to the starting position.","Repeat for the desired number of repetitions."], muscle_group: 'pectorals', api_key: "0033"),
  Exercise.create!(name: 'assisted side lying adductor stretch', description: ["Lie on your side with your legs straight and stacked on top of each other.","Bend your bottom leg slightly for stability.","Place your top foot on a stable surface, such as a bench or step.","Keeping your top leg straight, slowly lower it towards the ground, feeling a stretch in your inner thigh.","Hold the stretch for 20-30 seconds.","Return to the starting position and repeat on the other side."], muscle_group: 'adductors', api_key: "1712"),
  Exercise.create!(name: 'straight leg outer hip abductor', description: ["Lie on your side with your legs straight and stacked on top of each other.","Place your bottom arm under your head for support.","Engage your core and lift your top leg as high as possible without rotating your hips or leaning backward.","Pause for a moment at the top, then slowly lower your leg back down to the starting position.","Repeat for the desired number of repetitions, then switch sides."], muscle_group: 'abductors', api_key: "1427"),
  Exercise.create!(name: 'back extension on exercise ball', description: ["Place the stability ball on the ground and lie face down on top of it, with your hips resting on the ball and your feet against a wall or other stable surface.","Position your hands behind your head or crossed over your chest.","Engage your core and slowly lift your upper body off the ball, extending your back until your body forms a straight line from your head to your heels.","Pause for a moment at the top, then slowly lower your upper body back down to the starting position.","Repeat for the desired number of repetitions."], muscle_group: 'spine', api_key: "1314"),
  Exercise.create!(name: 'barbell incline bench press', description: ["Set up an incline bench at a 45-degree angle.","Lie down on the bench with your feet flat on the ground.","Grasp the barbell with an overhand grip, slightly wider than shoulder-width apart.","Unrack the barbell and lower it slowly towards your chest, keeping your elbows at a 45-degree angle.","Pause for a moment at the bottom, then push the barbell back up to the starting position.","Repeat for the desired number of repetitions."], muscle_group: 'pectorals', api_key: "0047"),
  Exercise.create!(name: 'barbell incline shoulder raise', description: ["Set up an incline bench at a 45-degree angle.","Sit on the bench with your back against the pad and feet flat on the ground.","Hold a barbell with an overhand grip, slightly wider than shoulder-width apart.","Lift the barbell up to shoulder height, keeping your elbows slightly bent.","Slowly raise the barbell overhead, extending your arms fully.","Pause for a moment at the top, then slowly lower the barbell back to shoulder height.","Repeat for the desired number of repetitions."], muscle_group: 'serratus anterior', api_key: "0050"),
  Exercise.create!(name: 'dumbbell incline bench press', description: ["Set up an incline bench at a 45-degree angle.","Sit on the bench with your feet flat on the ground and your back pressed firmly against the bench.","Hold a dumbbell in each hand, palms facing forward, and lift them to shoulder height.","Slowly lower the dumbbells to the sides of your chest, keeping your elbows at a 90-degree angle.","Push the dumbbells back up to the starting position, fully extending your arms.","Repeat for the desired number of repetitions."], muscle_group: 'pectorals', api_key: "0314"),
  Exercise.create!(name: 'smith full squat', description: ["Set up the smith machine with the barbell at shoulder height.","Stand with your feet shoulder-width apart, toes slightly turned out.","Step under the bar and position it across your upper back, resting on your traps.","Grip the bar with your hands slightly wider than shoulder-width apart.","Unrack the bar and take a step back, maintaining a stable stance.","Keeping your chest up and core engaged, initiate the squat by pushing your hips back and bending your knees.","Lower your body until your thighs are parallel to the ground, or as low as your flexibility allows.","Pause for a moment at the bottom, then drive through your heels to return to the starting position.","Repeat for the desired number of repetitions."], muscle_group: 'glutes', api_key: "3281"),
  Exercise.create!(name: 'dumbbell reverse wrist curl', description: ["Sit on a bench or chair with your feet flat on the ground.","Hold a dumbbell in each hand with an overhand grip, palms facing down.","Rest your forearms on your thighs, allowing your wrists to hang off the edge.","Slowly curl your wrists upward, bringing the dumbbells towards your body.","Pause for a moment at the top, then slowly lower the dumbbells back down to the starting position.","Repeat for the desired number of repetitions."], muscle_group: 'forearms', api_key: "0385"),
  Exercise.create!(name: 'band wrist curl', description: ["Sit on a bench or chair with your feet flat on the ground.","Hold the band with both hands, palms facing up, and rest your forearms on your thighs.","Slowly curl your wrists upward, squeezing your forearms.","Pause for a moment at the top, then slowly lower your wrists back down to the starting position.","Repeat for the desired number of repetitions."], muscle_group: 'forearms', api_key: "1016"),
  Exercise.create!(name: 'finger curls', description: ["Sit on a bench with your feet flat on the ground and hold a barbell with an underhand grip, palms facing up.","Rest your forearms on your thighs, allowing your wrists to hang off the edge.","Slowly curl your fingers towards your palms, squeezing the barbell tightly.","Hold the contraction for a moment, then slowly release your fingers back to the starting position.","Repeat for the desired number of repetitions."], muscle_group: 'forearms', api_key: "0455"),
  Exercise.create!(name: 'resistance band seated hip abduction', description: ["Sit on a chair or bench with your back straight and feet flat on the ground.","Wrap the resistance band around your thighs, just above your knees.","Place your hands on the sides of the chair or bench for support.","Engage your abductors (outer thigh muscles) and slowly push your knees apart, against the resistance of the band.","Pause for a moment at the end of the movement, then slowly bring your knees back together.","Repeat for the desired number of repetitions."], muscle_group: 'abductors', api_key: "3006"),
  Exercise.create!(name: 'barbell reverse preacher curl', description: ["Sit on a preacher bench with your chest against the pad and your arms extended straight down, holding a barbell with an overhand grip.","Keeping your upper arms stationary, exhale and curl the barbell upward while contracting your biceps.","Continue to raise the barbell until your biceps are fully contracted and the barbell is at shoulder level.","Hold the contracted position for a brief pause as you squeeze your biceps.","Inhale and slowly lower the barbell back to the starting position.","Repeat for the desired number of repetitions."], muscle_group: 'biceps', api_key: "0081"),
  Exercise.create!(name: 'barbell preacher curl', description: ["Sit on a preacher bench with your upper arms resting on the pad and your chest against the support.","Grasp the barbell with an underhand grip, slightly wider than shoulder-width apart.","Keeping your upper arms stationary, exhale and curl the barbell up towards your shoulders.","Pause for a moment at the top, squeezing your biceps.","Inhale and slowly lower the barbell back down to the starting position.","Repeat for the desired number of repetitions."], muscle_group: 'biceps', api_key: "0070"),
  Exercise.create!(name: 'ez barbell close grip preacher curl', description: ["Sit on a preacher curl bench and place your upper arms on the pad, gripping the ez barbell with an underhand grip.","Rest your triceps on the pad and fully extend your arms, keeping your back straight.","Slowly curl the barbell towards your shoulders, contracting your biceps.","Pause for a moment at the top, squeezing your biceps.","Lower the barbell back to the starting position, fully extending your arms.","Repeat for the desired number of repetitions."], muscle_group: 'biceps', api_key: "1627"),
  Exercise.create!(name: 'dumbbell incline triceps extension', description: ["Sit on an incline bench with a dumbbell in each hand, palms facing inwards.","Extend your arms fully overhead, keeping your elbows close to your head.","Lower the dumbbells behind your head by bending your elbows, keeping your upper arms stationary.","Pause for a moment, then raise the dumbbells back to the starting position by extending your arms.","Repeat for the desired number of repetitions."], muscle_group: 'triceps', api_key: "0330"),
  Exercise.create!(name: 'dumbbell preacher curl', description: ["Sit on a preacher curl bench with your upper arms resting on the pad and your chest against it.","Hold a dumbbell in each hand with your palms facing up and your arms fully extended.","Keeping your upper arms stationary, exhale and curl the weights while contracting your biceps.","Continue to raise the dumbbells until your biceps are fully contracted and the dumbbells are at shoulder level.","Hold the contracted position for a brief pause as you squeeze your biceps.","Inhale and slowly begin to lower the dumbbells back to the starting position.","Repeat for the desired number of repetitions."], muscle_group: 'biceps', api_key: "0372"),
  Exercise.create!(name: 'weighted tricep dips', description: ["Sit on the edge of a bench or chair with your hands gripping the edge next to your hips.","Slide your butt off the front of the bench with your legs extended in front of you.","Keep your back close to the bench and your elbows slightly bent.","Lower your body by bending your elbows until your upper arms are parallel to the floor.","Push yourself back up to the starting position by straightening your arms.","Repeat for the desired number of repetitions."], muscle_group: 'triceps', api_key: "1755"),
  Exercise.create!(name: 'elbow dips', description: ["Sit on the edge of a bench or chair with your hands gripping the edge next to your hips.","Slide your hips forward off the bench and straighten your legs, keeping your heels on the ground.","Bend your elbows and lower your body towards the ground, keeping your back close to the bench.","Pause for a moment at the bottom, then push through your hands to straighten your arms and lift your body back up to the starting position.","Repeat for the desired number of repetitions."], muscle_group: 'triceps', api_key: "3287"),
  Exercise.create!(name: 'triceps dip', description: ["Sit on the edge of a bench or chair with your hands gripping the edge, fingers pointing forward.","Slide your butt off the bench, supporting your weight with your hands.","Bend your elbows and lower your body towards the ground, keeping your back close to the bench.","Pause for a moment at the bottom, then push yourself back up to the starting position.","Repeat for the desired number of repetitions."], muscle_group: 'triceps', api_key: "0814"),
  Exercise.create!(name: 'assisted sit-up', description: ["Sit on the edge of a bench or have someone hold your feet down.","Lie flat on your back with your knees bent and feet flat on the ground.","Place your hands behind your head with your elbows pointing outwards.","Engaging your abs, slowly lift your upper body off the ground, curling forward until your torso is at a 45-degree angle.","Pause for a moment at the top, then slowly lower your upper body back down to the starting position.","Repeat for the desired number of repetitions."], muscle_group: 'abs', api_key: "1758"),
  Exercise.create!(name: 'butterfly yoga pose', description: ["Sit on the floor with your legs extended in front of you.","Bend your knees and bring the soles of your feet together, allowing your knees to fall out to the sides.","Hold onto your ankles or feet with your hands.","Sit up tall and lengthen your spine.","Gently press your knees down towards the floor, feeling a stretch in your inner thighs.","Hold this position for a few breaths.","To release, slowly bring your knees back up and extend your legs."], muscle_group: 'adductors', api_key: "1494"),
  Exercise.create!(name: 'spine stretch', description: ["Sit on the ground with your legs extended in front of you.","Place your hands on the ground behind you, fingers pointing towards your body.","Engage your core and slowly lean back, keeping your back straight.","Continue leaning back until you feel a stretch in your spine.","Hold the stretch for a few seconds, then slowly return to the starting position.","Repeat for the desired number of repetitions."], muscle_group: 'spine', api_key: "1363"),
  Exercise.create!(name: 'cable kickback', description: ["Stand facing a cable machine with your feet shoulder-width apart.","Hold the cable handle with your right hand and step back to create tension in the cable.","Bend your knees slightly and hinge forward at the hips, keeping your back straight.","Keep your upper arm close to your body and your elbow bent at a 90-degree angle.","Extend your forearm backward, straightening your arm fully.","Pause for a moment, then slowly return to the starting position.","Repeat for the desired number of repetitions, then switch sides."], muscle_group: 'triceps', api_key: "0860"),
  Exercise.create!(name: 'cable shrug', description: ["Stand facing the cable machine with your feet shoulder-width apart.","Grasp the cable handles with an overhand grip and let your arms hang down in front of you.","Keeping your arms straight, shrug your shoulders up towards your ears.","Hold the contraction for a moment, then slowly lower your shoulders back down to the starting position.","Repeat for the desired number of repetitions."], muscle_group: 'traps', api_key: "0220"),
  Exercise.create!(name: 'neck side stretch', description: ["Stand or sit up straight with your shoulders relaxed.","Tilt your head to one side, bringing your ear towards your shoulder.","Hold the stretch for 15-30 seconds.","Repeat on the other side.","Perform 2-4 sets on each side."], muscle_group: 'levator scapulae', api_key: "1403"),
  Exercise.create!(name: 'side push neck stretch', description: ["Stand or sit up straight with your shoulders relaxed.","Tilt your head to the right, bringing your right ear towards your right shoulder.","Place your right hand on the left side of your head and gently apply pressure to increase the stretch.","Hold the stretch for 15-30 seconds.","Repeat on the other side, tilting your head to the left and applying pressure with your left hand.","Repeat the stretch 2-3 times on each side."], muscle_group: 'levator scapulae', api_key: "0716"),
  Exercise.create!(name: 'dumbbell alternate biceps curl', description: ["Stand up straight with a dumbbell in each hand, palms facing forward and arms fully extended.","Keeping your upper arms stationary, exhale and curl the weights while contracting your biceps.","Continue to raise the dumbbells until your biceps are fully contracted and the dumbbells are at shoulder level.","Hold the contracted position for a brief pause as you squeeze your biceps.","Inhale and slowly begin to lower the dumbbells back to the starting position.","Repeat for the desired number of repetitions, alternating arms."], muscle_group: 'biceps', api_key: "0285"),
  Exercise.create!(name: 'dumbbell hammer curl', description: ["Stand up straight with a dumbbell in each hand, palms facing your torso.","Keep your elbows close to your torso and rotate the palms of your hands until they are facing forward.","This will be your starting position.","Now, keeping the upper arms stationary, exhale and curl the weights while contracting your biceps.","Continue to raise the weights until your biceps are fully contracted and the dumbbells are at shoulder level.","Hold the contracted position for a brief pause as you squeeze your biceps.","Then, inhale and slowly begin to lower the dumbbells back to the starting position.","Repeat for the recommended amount of repetitions."], muscle_group: 'biceps', api_key: "0313"),
  Exercise.create!(name: 'barbell standing close grip curl', description: ["Stand up straight with your feet shoulder-width apart and hold a barbell with an underhand grip, hands close together.","Keep your elbows close to your torso and your upper arms stationary throughout the movement.","Exhale as you curl the weights while contracting your biceps. Continue to raise the bar until your biceps are fully contracted and the bar is at shoulder level.","Hold the contracted position for a brief pause as you squeeze your biceps.","Inhale as you slowly begin to bring the barbell back to the starting position.","Repeat for the desired number of repetitions."], muscle_group: 'biceps', api_key: "0106"),
  Exercise.create!(name: 'barbell curl', description: ["Stand up straight with your feet shoulder-width apart and hold a barbell with an underhand grip, palms facing forward.","Keep your elbows close to your torso and exhale as you curl the weights while contracting your biceps.","Continue to raise the bar until your biceps are fully contracted and the bar is at shoulder level.","Hold the contracted position for a brief pause as you squeeze your biceps.","Inhale as you slowly begin to lower the bar back to the starting position.","Repeat for the desired number of repetitions."], muscle_group: 'biceps', api_key: "0031"),
  Exercise.create!(name: 'upper back stretch', description: ["Stand up straight with your feet shoulder-width apart.","Extend your arms straight in front of you, parallel to the ground.","Interlace your fingers and rotate your palms away from your body.","Slowly raise your arms overhead, keeping them straight and parallel to each other.","As you raise your arms, squeeze your shoulder blades together.","Hold the stretch for 15-30 seconds, then release and repeat."], muscle_group: 'upper back', api_key: "1365"),
  Exercise.create!(name: 'cable lateral raise', description: ["Stand with your feet shoulder-width apart and grasp the cable handles with an overhand grip.","Keep your arms straight and your core engaged.","Raise your arms out to the sides until they are parallel to the floor.","Pause for a moment at the top, then slowly lower your arms back down to the starting position.","Repeat for the desired number of repetitions."], muscle_group: 'delts', api_key: "0178"),
  Exercise.create!(name: 'barbell shrug', description: ["Stand with your feet shoulder-width apart and hold a barbell in front of you with an overhand grip.","Keep your arms straight and your back straight throughout the exercise.","Lift your shoulders up towards your ears as high as possible, squeezing your traps at the top.","Hold for a moment, then slowly lower your shoulders back down to the starting position.","Repeat for the desired number of repetitions."], muscle_group: 'traps', api_key: "0095"),
  Exercise.create!(name: 'barbell standing twist', description: ["Stand with your feet shoulder-width apart and hold a barbell in front of your chest with both hands, palms facing down.","Engage your core and keep your back straight throughout the exercise.","Slowly twist your torso to the right, pivoting on your feet and hips, while keeping your lower body stable.","Pause for a moment at the end of the twist, then slowly return to the starting position.","Repeat the twist to the left side.","Continue alternating twists for the desired number of repetitions."], muscle_group: 'abs', api_key: "0112"),
  Exercise.create!(name: 'barbell front raise', description: ["Stand with your feet shoulder-width apart and hold a barbell in front of your thighs with an overhand grip.","Keep your arms straight and lift the barbell forward and upward until it reaches shoulder level.","Pause for a moment at the top, then slowly lower the barbell back down to the starting position.","Repeat for the desired number of repetitions."], muscle_group: 'delts', api_key: "0041"),
  Exercise.create!(name: 'dumbbell shrug', description: ["Stand with your feet shoulder-width apart and hold a dumbbell in each hand with your palms facing your body.","Keep your arms straight and let the dumbbells hang by your sides.","Raise your shoulders as high as possible, as if you are trying to touch your ears with your shoulders.","Hold the contraction for a second, then slowly lower your shoulders back down to the starting position.","Repeat for the desired number of repetitions."], muscle_group: 'traps', api_key: "0406"),
  Exercise.create!(name: 'dumbbell lateral raise', description: ["Stand with your feet shoulder-width apart and hold a dumbbell in each hand, palms facing your body.","Keep your back straight and engage your core.","Raise your arms out to the sides until they are parallel to the floor, keeping a slight bend in your elbows.","Pause for a moment at the top, then slowly lower your arms back down to the starting position.","Repeat for the desired number of repetitions."], muscle_group: 'delts', api_key: "0334"),
  Exercise.create!(name: 'bodyweight standing row', description: ["Stand with your feet shoulder-width apart and knees slightly bent.","Grasp a bar or handles with an overhand grip, palms facing down.","Keep your back straight and core engaged.","Pull the bar or handles towards your body, squeezing your shoulder blades together.","Pause for a moment at the top of the movement.","Slowly release and extend your arms back to the starting position.","Repeat for the desired number of repetitions."], muscle_group: 'upper back', api_key: "3166"),
  Exercise.create!(name: 'band straight leg deadlift', description: ["Stand with your feet shoulder-width apart and place the band around your feet.","Hold the band with both hands, palms facing your body, and keep your arms straight.","Engage your core and maintain a slight bend in your knees.","Slowly hinge forward at your hips, keeping your back straight and chest lifted.","Lower the band towards the ground while keeping your legs straight.","Pause for a moment at the bottom, then squeeze your glutes and hamstrings to return to the starting position.","Repeat for the desired number of repetitions."], muscle_group: 'spine', api_key: "1010"),
  Exercise.create!(name: 'barbell deadlift', description: ["Stand with your feet shoulder-width apart and the barbell on the ground in front of you.","Bend your knees and hinge at the hips to lower your torso and grip the barbell with an overhand grip, hands slightly wider than shoulder-width apart.","Keep your back straight and chest lifted as you drive through your heels to lift the barbell off the ground, extending your hips and knees.","As you stand up straight, squeeze your glutes and keep your core engaged.","Lower the barbell back down to the ground by bending at the hips and knees, keeping your back straight.","Repeat for the desired number of repetitions."], muscle_group: 'glutes', api_key: "0032"),
  Exercise.create!(name: 'side hip abduction', description: ["Stand with your feet shoulder-width apart and your hands on your hips.","Shift your weight to one leg and lift the opposite leg out to the side, keeping it straight.","Pause for a moment at the top, then slowly lower your leg back down to the starting position.","Repeat on the other side.","Continue alternating sides for the desired number of repetitions."], muscle_group: 'abductors', api_key: "0710"),
  Exercise.create!(name: 'barbell pendlay row', description: ["Stand with your feet shoulder-width apart and your knees slightly bent.","Bend forward at the hips, keeping your back straight and your chest up.","Grasp the barbell with an overhand grip, slightly wider than shoulder-width apart.","Pull the barbell towards your upper abdomen, squeezing your shoulder blades together.","Lower the barbell back down to the starting position.","Repeat for the desired number of repetitions."], muscle_group: 'upper back', api_key: "3017"),
  Exercise.create!(name: 'barbell straight leg deadlift', description: ["Stand with your feet shoulder-width apart and your toes pointing forward.","Hold the barbell with an overhand grip, hands slightly wider than shoulder-width apart.","Bend at your hips and lower the barbell towards the ground, keeping your back straight and your knees slightly bent.","Lower the barbell until you feel a stretch in your hamstrings.","Engage your hamstrings and glutes to lift the barbell back up to the starting position.","Repeat for the desired number of repetitions."], muscle_group: 'hamstrings', api_key: "0116"),
  Exercise.create!(name: 'cable twist', description: ["Stand with your feet shoulder-width apart, facing the cable machine.","Hold the cable handle with both hands in front of your chest, keeping your arms slightly bent.","Engage your core and twist your torso to the right, pulling the cable across your body.","Pause for a moment at the end of the movement, feeling the contraction in your abs and obliques.","Slowly return to the starting position, resisting the cable's pull.","Repeat the movement to the left side.","Continue alternating sides for the desired number of repetitions."], muscle_group: 'abs', api_key: "0243"),
  Exercise.create!(name: 'barbell lateral lunge', description: ["Stand with your feet shoulder-width apart, holding a barbell across your upper back.","Take a big step to the side with your right foot, keeping your left foot planted.","Bend your right knee and lower your body down into a lunge position, keeping your left leg straight.","Push off with your right foot and return to the starting position.","Repeat on the other side, stepping with your left foot."], muscle_group: 'glutes', api_key: "1410"),
  Exercise.create!(name: 'dumbbell push press', description: ["Stand with your feet shoulder-width apart, holding a dumbbell in each hand at shoulder level.","Bend your knees slightly and dip your body down, then explosively extend your legs and press the dumbbells overhead.","Lock out your arms at the top of the movement, then lower the dumbbells back to shoulder level.","Repeat for the desired number of repetitions."], muscle_group: 'delts', api_key: "1700"),
  Exercise.create!(name: 'dumbbell upright row', description: ["Stand with your feet shoulder-width apart, holding a dumbbell in each hand with an overhand grip.","Let the dumbbells hang in front of your thighs, with your arms fully extended.","Keeping your back straight and your core engaged, exhale and lift the dumbbells straight up towards your chin, leading with your elbows.","Pause for a moment at the top, then inhale and slowly lower the dumbbells back down to the starting position.","Repeat for the desired number of repetitions."], muscle_group: 'delts', api_key: "0437"),
  Exercise.create!(name: 'kettlebell hang clean', description: ["Stand with your feet shoulder-width apart, holding a kettlebell in front of your thighs.","Bend your knees slightly and hinge forward at the hips, keeping your back straight.","Lower the kettlebell towards the ground, allowing it to swing between your legs.","Quickly extend your hips and knees, using the momentum to swing the kettlebell up to shoulder height.","As the kettlebell reaches shoulder height, rotate your wrists and catch the kettlebell in the rack position, with your elbow tucked in and the kettlebell resting on your forearm.","Lower the kettlebell back down to the starting position between your legs, and repeat for the desired number of repetitions."], muscle_group: 'hamstrings', api_key: "0535"),
  Exercise.create!(name: 'bodyweight standing calf raise', description: ["Stand with your feet shoulder-width apart, toes pointing forward.","Place your hands on a wall or stable surface for balance.","Slowly raise your heels off the ground, lifting your body weight onto the balls of your feet.","Pause for a moment at the top, then slowly lower your heels back down to the starting position.","Repeat for the desired number of repetitions."], muscle_group: 'calves', api_key: "1373"),
  Exercise.create!(name: 'barbell full squat', description: ["Stand with your feet shoulder-width apart, toes slightly turned out.","Hold the barbell across your upper back, resting it on your traps or rear delts.","Engage your core and keep your chest up as you begin to lower your body down.","Bend at the knees and hips, pushing your hips back and down as if sitting into a chair.","Lower yourself until your thighs are parallel to the ground or slightly below.","Keep your knees in line with your toes and your weight in your heels.","Drive through your heels to stand back up, extending your hips and knees.","Repeat for the desired number of repetitions."], muscle_group: 'glutes', api_key: "0043"),
  Exercise.create!(name: 'forward jump', description: ["Stand with your feet shoulder-width apart.","Bend your knees and lower your body into a squat position.","Swing your arms back for momentum.","Jump forward explosively, extending your hips, knees, and ankles.","Land softly on the balls of your feet and immediately go into the next jump.","Repeat for the desired number of repetitions."], muscle_group: 'quads', api_key: "1472"),
  Exercise.create!(name: 'hamstring stretch', description: ["Stand with your feet shoulder-width apart.","Step forward with your right foot and shift your weight onto your right leg.","Keeping your back straight, slowly bend forward at the hips, reaching towards your right foot with both hands.","Hold the stretch for 20-30 seconds, then return to the starting position.","Repeat on the other side."], muscle_group: 'hamstrings', api_key: "1511"),
  Exercise.create!(name: 'donkey calf raise', description: ["Stand with your toes on an elevated surface, such as a step or block.","Place your hands on a stable support, such as a wall or railing, for balance.","Raise your heels as high as possible, lifting your body weight onto the balls of your feet.","Pause for a moment at the top, then slowly lower your heels back down to the starting position.","Repeat for the desired number of repetitions."], muscle_group: 'calves', api_key: "0284"),
  Exercise.create!(name: 'skin the cat', description: ["Start by hanging from a bar with your arms fully extended and your body relaxed.","Engage your core and lift your legs up, bringing your knees towards your chest.","Continue to lift your legs up and over your head, allowing your body to pass through the arms.","Once your legs are fully extended over your head, begin to lower them back down towards the starting position.","As you lower your legs, allow your body to pass back through the arms until you are hanging with your arms fully extended again.","Repeat for the desired number of repetitions."], muscle_group: 'upper back', api_key: "3304"),
  Exercise.create!(name: 'muscle up', description: ["Start by hanging from a pull-up bar with your palms facing away from you and your arms fully extended.","Engage your core and pull your body up towards the bar, leading with your chest.","As you reach the top of the movement, transition your grip so that your palms are facing towards you.","Continue pulling yourself up until your chest is above the bar and your arms are fully flexed.","Reverse the movement by slowly lowering yourself back down to the starting position.","Repeat for the desired number of repetitions."], muscle_group: 'lats', api_key: "0631"),
  Exercise.create!(name: 'side plank hip adduction', description: ["Start by lying on your side with your legs extended and stacked on top of each other.","Prop yourself up on your forearm, keeping your elbow directly below your shoulder.","Engage your core and lift your hips off the ground, creating a straight line from your head to your feet.","While maintaining the side plank position, lift your top leg towards the ceiling, keeping it straight.","Slowly lower your leg back down to the starting position.","Repeat for the desired number of repetitions, then switch sides."], muscle_group: 'adductors', api_key: "1775"),
  Exercise.create!(name: 'run', description: ["Start by standing upright with your feet hip-width apart.","Engage your core and keep your upper body relaxed.","Begin jogging in place, lifting your knees up towards your chest and landing softly on the balls of your feet.","Maintain a steady pace and continue jogging for the desired duration or distance.","Remember to breathe deeply and maintain good posture throughout the exercise."], muscle_group: 'cardiovascular system', api_key: "0685"),
  Exercise.create!(name: 'barbell lunge', description: ["Start by standing with your feet shoulder-width apart and a barbell resting on your upper back.","Take a step forward with your right foot, keeping your torso upright.","Lower your body by bending your right knee until your thigh is parallel to the ground.","Push through your right heel to return to the starting position.","Repeat with your left leg, alternating legs for the desired number of repetitions."], muscle_group: 'glutes', api_key: "0054"),
  Exercise.create!(name: 'barbell hack squat', description: ["Start by standing with your feet shoulder-width apart and your toes slightly turned out.","Hold the barbell behind your legs, resting it on your upper thighs.","Lower your body by bending at the knees and hips, keeping your back straight and your chest up.","Continue lowering until your thighs are parallel to the ground, or as low as you can comfortably go.","Pause for a moment, then push through your heels to return to the starting position.","Repeat for the desired number of repetitions."], muscle_group: 'glutes', api_key: "0046"),
  Exercise.create!(name: 'lunge with jump', description: ["Start by standing with your feet shoulder-width apart.","Take a step forward with your right foot, lowering your body into a lunge position.","Push off with your right foot and jump into the air, switching the position of your feet mid-air.","Land softly with your left foot forward and immediately lower your body into a lunge position.","Continue alternating between lunges and jumps for the desired number of repetitions."], muscle_group: 'glutes', api_key: "3582"),
  Exercise.create!(name: 'diamond push-up', description: ["Start in a high plank position with your hands close together, forming a diamond shape with your thumbs and index fingers.","Keep your body in a straight line from head to toe, engaging your core and glutes.","Lower your chest towards the diamond shape formed by your hands, keeping your elbows close to your body.","Pause for a moment at the bottom, then push yourself back up to the starting position.","Repeat for the desired number of repetitions."], muscle_group: 'triceps', api_key: "0283"),
  Exercise.create!(name: 'mountain climber', description: ["Start in a high plank position with your hands directly under your shoulders and your body in a straight line.","Engage your core and bring your right knee towards your chest, then quickly switch and bring your left knee towards your chest.","Continue alternating legs in a running motion, keeping your hips low and your core engaged.","Maintain a steady pace and breathe evenly throughout the exercise.","Repeat for the desired number of repetitions."], muscle_group: 'cardiovascular system', api_key: "0630"),
  Exercise.create!(name: 'close-grip push-up', description: ["Start in a high plank position with your hands placed close together, directly under your shoulders.","Engage your core and lower your body towards the ground, keeping your elbows close to your sides.","Push through your palms to extend your arms and return to the starting position.","Repeat for the desired number of repetitions."], muscle_group: 'triceps', api_key: "0259"),
  Exercise.create!(name: 'push-up', description: ["Start in a high plank position with your hands slightly wider than shoulder-width apart and your feet together.","Engage your core and lower your body towards the ground by bending your elbows, keeping your body in a straight line.","Pause for a moment when your chest is just above the ground, then push yourself back up to the starting position by straightening your arms.","Repeat for the desired number of repetitions."], muscle_group: 'pectorals', api_key: "0662"),
  Exercise.create!(name: 'push-up to side plank', description: ["Start in a push-up position with your hands shoulder-width apart and your body in a straight line.","Lower your body towards the ground by bending your elbows, keeping your core engaged.","Push back up to the starting position.","Shift your weight onto your left hand and rotate your body to the right, lifting your right arm towards the ceiling.","Hold the side plank position for a few seconds, then return to the starting position.","Repeat the push-up and side plank on the opposite side.","Continue alternating sides for the desired number of repetitions."], muscle_group: 'abs', api_key: "0664"),
  Exercise.create!(name: 'burpee', description: ["Start in a standing position with your feet shoulder-width apart.","Lower your body into a squat position by bending your knees and placing your hands on the floor in front of you.","Kick your feet back into a push-up position.","Perform a push-up, keeping your body in a straight line.","Jump your feet back into the squat position.","Jump up explosively, reaching your arms overhead.","Land softly and immediately lower back into a squat position to begin the next repetition."], muscle_group: 'cardiovascular system', api_key: "1160")
]

# Define static workout dates
static_dates = [
  '2024-10-01', '2024-10-04', '2024-10-07', # Week 1
  '2024-10-10', '2024-10-13', '2024-10-16', # Week 2
  '2024-10-19', '2024-10-22', '2024-10-25', # Week 3
  '2024-10-28', '2024-11-01', '2024-11-04', # Week 4
  '2024-11-07', '2024-11-10', '2024-11-13', # Week 5
  '2024-11-16', '2024-11-19', '2024-11-22'  # Week 6
]

# Generate workouts, workout_exercises, and set_entries
static_dates.each_with_index do |date, index|
  users.each do |user|
    # Create a workout for each user
    workout = Workout.create!(user: user, date: date, notes: "Workout session #{index + 1} for #{user.name}")

    # Select 3-5 random exercises for the workout
    selected_exercises = exercises.first(10).sample(rand(3..5))

    selected_exercises.each_with_index do |exercise, ex_index|
      # Create a workout_exercise entry
      workout_exercise = WorkoutExercise.create!(workout: workout, exercise: exercise)

      # Generate 3-4 sets for each exercise
      (1..rand(3..4)).each do |set_number|
        # Weight calculation based on the revised logic
        base_weight = (exercise.api_key.to_s[-2..].to_i) + (index * 2) + ex_index * 5
        SetEntry.create!(
          workout_exercise: workout_exercise,
          set_number: set_number,
          reps: rand(8..12), # Random reps between 8 and 12
          weight: base_weight + set_number * 2 # Incremental weight for each set
        )
      end
    end
  end
end


puts "Static seed data with static dates created successfully!"